# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/mt6879-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mt6879-common)

endif
